markdown: kramdown
kramdown: 
  hard_wrap: false
  line_width: 120
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - guide.md

theme: jekyll-theme-slate